# Site settings
title: Marek Narozniak
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "https://mareknarozniak.com" # default is empty

# Build settings
kramdown:
  input: GFM
  math_engine: katex
  math_engine_opts: {throw_on_error: true}
permalink: pretty

plugins:
  - jekyll-seo-tag

# extra directories
include: 
  - .well-known

# Third-party services
# just leave empty to disable it
google_analytics: "UA-93578712-1"
disqus_shortname:

# Bibliography
scholar:
  style: _data/apa2.csl
  bibliography_template: bib

# for jekyll-seo-tag plugin

title: Marek Narozniak's Homepage

# livestream variables

liveyoutube: https://www.youtube.com/channel/UCyKg9ULXBgUyXoKcFL9BpVw/videos?view=2&sort=dd&live_view=502&shelf_id=0
livefb: https://www.facebook.com/marekstreams
livefbevents: https://www.facebook.com/marekstreams/events/

# tagline:

author: mareknarozniak

twitter:
  username: MarekNarozniak
  card: summary

social:
  name: Marek Narozniak
  links:
    - https://twitter.com/MarekNarozniak
    - https://twitter.com/komentoid
    - https://www.linkedin.com/in/mareknarozniak
    - https://github.com/marekyggdrasil
