# Site settings
title: Marek Narozniak
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "https://mareknarozniak.com" # default is empty

# Build settings
kramdown:
  input: GFM
  math_engine: katex
  math_engine_opts: {throw_on_error: true}
permalink: pretty

plugins:
  - jekyll-seo-tag

# extra directories
include: ['.well-known']

# Third-party services
# just leave empty to disable it
google_analytics: "UA-93578712-1"
disqus_shortname:
# scholar:
#  style: mla

# for jekyll-seo-tag plugin

title: Marek Narozniak's Homepage
# tagline:

author: mareknarozniak

twitter:
  username: MarekNarozniak
  card: summary

social:
  name: Marek Narozniak
  links:
    - https://twitter.com/MarekNarozniak
    - https://twitter.com/komentoid
    - https://www.linkedin.com/in/mareknarozniak
    - https://github.com/marekyggdrasil
